[workspace]

members = [
    "treewidth_heuristic",
    "dimacs_benchmarks",
    "k_tree_benchmarks"
]
resolver = "2"

# Optimization in debug mode for own code
[profile.dev]
opt-level = 1

# Optimiziation in debug mode for dependencies
[profile.dev.package."*"]
opt-level = 1