[package]
name = "clique_graph_treewidth_heuristic"
version = "0.1.0"
edition = "2021"
rust-version = "1.76"
authors = ["Raoul Luque <raoulsluque@gmail.com>"]
description = "A heuristic for calculating an upper bound on treewidth of graphs using clique-graphs"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
petgraph = "0.6.4"
itertools = "0.12.1"
rand = "0.8.5"